import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './(components)/Navigation';

// Getting Font Awesome CSS to Work with Nextjs
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata = {
	title: 'Ticket Next App',
	description: 'Generated by jagokode',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="flex flex-col h-screen max-h-screen">
				<Navigation />
				<main className="flex-grow overflow-y-auto bg-page text-default-text">
					{children}
				</main>
				<footer className="flex justify-center py-4 bg-footer text-default-text">
					&copy; jagokode 2023
				</footer>
			</body>
		</html>
	);
}
